export enum ErrorCode {
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  ANALYSIS_QUOTA_EXCEEDED = 'ANALYSIS_QUOTA_EXCEEDED',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_TIME_RANGE = 'INVALID_TIME_RANGE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Log Sources
  LOG_SOURCE_CONNECTION_FAILED = 'LOG_SOURCE_CONNECTION_FAILED',
  LOG_SOURCE_QUERY_FAILED = 'LOG_SOURCE_QUERY_FAILED',
  LOG_SOURCE_NOT_CONFIGURED = 'LOG_SOURCE_NOT_CONFIGURED',

  // Code Repos
  REPO_CONNECTION_FAILED = 'REPO_CONNECTION_FAILED',
  REPO_NOT_CONFIGURED = 'REPO_NOT_CONFIGURED',
  REPO_FILE_NOT_FOUND = 'REPO_FILE_NOT_FOUND',
  FEATURE_NOT_AVAILABLE = 'FEATURE_NOT_AVAILABLE',

  // Analysis
  ANALYSIS_NOT_FOUND = 'ANALYSIS_NOT_FOUND',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',
  LLM_ERROR = 'LLM_ERROR',

  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
}
